DROP TABLE IF EXISTS realEstateCa;

CREATE TABLE realEstateCa (
	id	VARCHAR,
	stateId	NUMERIC,
	countyId NUMERIC,
	cityId NUMERIC,
	country VARCHAR,
	datePostedString DATE,
	is_bankOwned BOOLEAN,
	is_forAuction BOOLEAN,
	event VARCHAR,
	time NUMERIC,
	price NUMERIC,
	pricePerSquareFoot NUMERIC,
	city VARCHAR,
	state VARCHAR,
	yearBuilt NUMERIC,
	streetAddress VARCHAR,
	zipcode NUMERIC,
	longitude NUMERIC,	
	latitude NUMERIC,
	hasBadGeocode BOOLEAN,
	description TEXT, 
	currency VARCHAR, 
	livingArea NUMERIC, 
	livingAreaValue NUMERIC,
	lotAreaUnits VARCHAR,	
	bathrooms NUMERIC,
	bedrooms NUMERIC,
	buildingArea NUMERIC, 
	parking BOOLEAN, 	
	garageSpaces NUMERIC,
	hasGarage BOOLEAN,
	levels VARCHAR,
	pool BOOLEAN,
	spa BOOLEAN,
	isNewConstruction BOOLEAN,
	hasPetsAllowed BOOLEAN,
	homeType VARCHAR,
	county VARCHAR
);